### ISSUE TITLE
Comments' background

### ISSUE THREAD

**Issue by delminskii** [morhetz/gruvbox#91]
Hello. I like this theme very much. I use vim 7.4 in terminal (xterm) on debian 7.9. I had to add gruvbox-256-colors.sh at the end of my .bashrc, the colors are applied good enough.  But the problem is in comments' background on some files (for example, *.sh, *.py). A line beginning with crunch (#) has background highlight, which I do not want to have. Is that normal behavior? How to fix that? I think I should remove/comment some line in gruvbox/gruvbox-256-colors.sh script.

Take a look at the attachment please: a top side is a chunk of bash file, and the bottom side is the chunk of python file 
![12](https://cloud.githubusercontent.com/assets/6321554/12209807/916bc2d2-b666-11e5-80d7-dd6c6bab0e76.png)

**Comment by morhetz** [comment]
@delminskii 
Doh, that's weird. Can't get my hands at linux box currently.
Could try reproducing this with other terminal emulators like urxvt or gnome-terminal while I'm investigating the issue?

**Comment by delminskii** [comment]
@morhetz 
I've tested `rxvt`, `rxvt-unicode` (urxvt?), `lxterm` and `uxterm` - there's the same problem everywhere.

**Comment by morhetz** [comment]
It would help if you could share your `.vimrc`.
What's the output of `:let g:gruvbox_italic`? Any chance you've enforced displaying italics with non-compatible term (`let g:gruvbox_italic=1`)?
What's your `$TERM` shell variable set up to? Do run vim inside tmux?

**Comment by delminskii** [comment]
The output of `:let g:gruvbox_italic` is `#1`;
`$TERM` is `xterm-256color`
My current `vimrc` is [here](https://gist.github.com/delminskii/32531f1f1ec0455d2eaa)
There's the same behavior inside of tmux.

**Comment by morhetz** [comment]
> The output of :let g:gruvbox_italic is #1;

Oh, that's the reason why comments are get inverted. Seems like [this check](https://github.com/morhetz/gruvbox/blob/master/colors/gruvbox.vim#L32) got interpreted wrong. It is obviously could be only if your `$TERM_ITALICS` shell var is set up incorrectly since your term emulator can't handle italics correctly. That's weird cause I'm sure `rxvt-unicode` should be ok with that.

Anyway, here are two different solutions.
1. You could enforce disabling italics at your `.vimrc` like this:
```
" =============================================================================
" Gruvbox colorscheme settings
" =============================================================================
set background=dark
let g:gruvbox_italic=0
let g:gruvbox_contrast_dark='hard'
colorscheme gruvbox
```
NB: It's advised that you put gruvbox settings **above** the line `colorscheme gruvbox`
2. Try investigating why the environment variable `$TERM_ITALICS` is set to `true` and handle that correctly anyway

**Comment by delminskii** [comment]
@morhetz 
oh, yes. The first solution has helped. It truthy cool now. Thanks you very much for the help, it was my mistake.

**Comment by morhetz** [comment]
@delminskii 
:+1:
